### ISSUE TITLE
Crash after some time

### ISSUE THREAD

**Issue by hookro** [kallefrombosnia/hlds-log#2]
```
/root/DiscordBot/node_modules/hlds-log/functions.js:63
        this.emit(type.event, type);
                       ^

TypeError: Cannot read property 'event' of undefined
    at /root/DiscordBot/node_modules/hlds-log/functions.js:63:24
    at Array.forEach (<anonymous>)
    at HLDS_Log.regexSearch (/root/DiscordBot/node_modules/hlds-log/functions.js:60:16)
    at Socket.<anonymous> (/root/DiscordBot/node_modules/hlds-log/functions.js:48:12)
    at Socket.emit (events.js:315:20)
```

``` root@ubuntu-2gb-nbg1-1: ~
? nodejs -v
v12.17.0
```

**Comment by kallefrombosnia** [comment]
Try to see what message caused that error. 
When you type `log on ` server starts localy to write to specfic log file. Last lines should tell what caused the problem.

Also I will push update to prevent this type of errors, hopefully.

**Comment by hookro** [comment]
I will check it again in couple of days, I added in the helpers.js some checks so it won't crash again which hasn't but I didn't checked really because it happened overnight.

**Comment by kallefrombosnia** [comment]
I noticed when user close log file, server still sends some information over remote like integer ` 11 `, probably something like that crashed but now all should be fine.
